apiVersion: v1
kind: Pod
metadata:
  labels:
    app: my-standalone-svc
    controller: mongodb-enterprise-operator
    controller-revision-hash: my-standalone-5f874b46df
    pod-anti-affinity: my-standalone
    statefulset.kubernetes.io/pod-name: my-standalone-0
  name: the-standalone-0
  namespace: mongodb
spec:
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              pod-anti-affinity: my-standalone
          topologyKey: kubernetes.io/hostname
        weight: 100
  containers:
  - command: [ "/bin/bash", "-c", "sleep", "3600" ]
    env:
    - name: AGENT_API_KEY
      valueFrom:
        secretKeyRef:
          key: agentApiKey
          name: 5f849101e9408c2a969515ed-group-secret
    - name: AGENT_FLAGS
      value: -logFile,/var/log/mongodb-mms-automation/automation-agent.log,
    - name: BASE_URL
      value: http://ops-manager-svc.mongodb.svc.cluster.local:8080
    - name: GROUP_ID
      value: 5f849101e9408c2a969515ed
    - name: LOG_LEVEL
    - name: SSL_REQUIRE_VALID_MMS_CERTIFICATES
      value: "true"
    - name: USER_LOGIN
      value: TPUQYRIK
    image: quay.io/mongodb/mongodb-enterprise-database:2.0.0
    imagePullPolicy: Always
    livenessProbe:
      exec:
        command:
        - /opt/scripts/probe.sh
      failureThreshold: 6
      initialDelaySeconds: 60
      periodSeconds: 30
      successThreshold: 1
      timeoutSeconds: 30
    name: mongodb-enterprise-database
    ports:
    - containerPort: 27017
      protocol: TCP
    readinessProbe:
      exec:
        command:
        - /opt/scripts/readinessprobe
      failureThreshold: 240
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: "2"
        memory: 700m
      requests:
        cpu: "1"
        memory: 500m
    securityContext:
      runAsNonRoot: true
      runAsUser: 2000
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /opt/scripts
      name: database-scripts
      readOnly: true
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: mongodb-enterprise-database-pods-token-79v8j
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: my-standalone-0
  nodeName: ip-10-231-67-160.us-east-2.compute.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 2000
  serviceAccount: mongodb-enterprise-database-pods
  serviceAccountName: mongodb-enterprise-database-pods
  subdomain: my-standalone-svc
  terminationGracePeriodSeconds: 600
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: database-scripts
  - name: mongodb-enterprise-database-pods-token-79v8j
    secret:
      defaultMode: 420
      secretName: mongodb-enterprise-database-pods-token-79v8j
