# REF: https://docs.mongodb.com/kubernetes-operator/stable/tutorial/plan-om-resource/#om-rsrc-prereqs
bases:
  - ../application
#patchesStrategicMerge:
#  - mongodb-enterprise.yaml
secretGenerator:
- name: ops-manager
  namespace: mongodb
  literals:
  - password=Password123!
- name: aws-s3-credentials
  namespace: mongodb
  literals:
  - accessKey=123
  - secretKey=456
generatorOptions:
  disableNameSuffixHash: true
