# REF: https://docs.mongodb.com/kubernetes-operator/stable/tutorial/plan-om-resource/#om-rsrc-prereqs
bases:
  - ../application
patchesStrategicMerge:
  - mongodb-enterprise.yaml
secretGenerator:
- name: adminusercredentials
  namespace: mongodb
  literals:
  - Username=admin
  - FirstName=Admin
  - LastName=User
  files:
  - Password
generatorOptions:
  disableNameSuffixHash: true
